server:
  port: 9903
---
spring:
  datasource:
    username: bulletin
    password: 1234
    url: jdbc:mariadb://localhost:3306/bulletin
    driver-class-name: org.mariadb.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    open-in-view: false

util:
  encrypt:
    secretKey: zoqkfow29fj20fchg95761kjfsd343tw
  jwt:
    secretKey: fwjf91kfoqiwuejcuzghqpmvzzd39qmk
    refreshKey: fwjf91kfoqiwuejcuzghqpmvzzd39qmk
    defaultExpirationMinutes: 60

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.seung.pilot